tab_spaces                          = 2
max_width                           = 80
format_code_in_doc_comments         = true
format_macro_bodies                 = true
format_macro_matchers               = true
imports_granularity                 = "Item"
match_arm_leading_pipes             = "Always"
imports_layout                      = "HorizontalVertical"
imports_indent                      = "Block"
group_imports                       = "StdExternalCrate"
newline_style                       = "Native"
reorder_impl_items                  = true
struct_lit_width                    = 50
struct_lit_single_line              = true
struct_field_align_threshold        = 30
array_width                         = 15
short_array_element_width_threshold = 15
